### ISSUE TITLE
join forces?

### ISSUE THREAD

**Issue by mfrasca** [KitaitiMakoto/epub-maker#1]
hi here, I am the author of a similarly named Python program, with the same goal.
care to join forces? mfrasca/txt2epub#14

**Comment by KitaitiMakoto** [comment]
Hello,

Thanks for your message. It looks interesting.

But this project completely targets to Ruby and mainly focuses to in-place editing rather than generate EPUB books from text files.
Although glad to invitation, I won't to join to your project.

No offence, thanks.
